"use client";
import Header from "./Header";
import "./globals.css";
import Providers from "./components/Providers";

import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
  gql,
} from "@apollo/client";

export const metadata = {
  title: "ARTEMIS NEWS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const client = new ApolloClient({
    uri: "http://localhost:5000/graphql",
    cache: new InMemoryCache(),
  });
  return (
    <html lang="en">
      <body
        className="
        bg-gray-100
        dark:bg-zinc-900
        transition-all duration-700"
      >
        <ApolloProvider client={client}>
          <Providers>
            <Header />
            <div className="max-w-6xl mx-auto">{children}</div>
          </Providers>
        </ApolloProvider>
      </body>
    </html>
  );
}
